name: flutter_news_app_getx_rewrite2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  logger: ^1.3.0
  easy_splash_screen: ^1.0.4
  card_swiper: ^2.0.4
  webview_flutter: ^2.1.1
  cached_network_image: ^3.2.3
  skeletons: ^0.0.3
  flutter_launcher_icons: ^0.13.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 
  

flutter:
  assets:
    - assets/images/
  uses-material-design: true

